name: flame_mcp_server
description: Local MCP server providing on-demand Flame engine documentation from GitHub
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  http: ^1.1.0
  html: ^0.15.4
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  flame_mcp_server:
