name: Sync Flame Documentation

on:
  schedule:
    # Run at 2 AM UTC daily
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]  # Also run on pushes to main

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
          
      - name: Install dependencies
        run: dart pub get
        
      - name: Sync documentation from GitHub
        run: dart run bin/flame_sync.dart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate static MCP API
        run: dart run bin/generate_static_api.dart
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './api_output'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
